In [1]:
import json

with open('1_scrapping_black_clover.json', 'r') as openfile:
    eps_summary = json.load(openfile)

with open('3_characters_black_clover.json', 'r') as openfile:
    characters = json.load(openfile)

with open('3_overused_verbs_black_clover.json', 'r') as openfile:
    overused_verbs = json.load(openfile)

In [2]:
overused_verbs_lowered = []
for verb in overused_verbs:
    overused_verbs_lowered.append(verb)

In [3]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

[nltk_data] Downloading package punkt to /home/pauli/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/pauli/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to /home/pauli/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!


True

In [4]:
from nltk import word_tokenize
from nltk import sent_tokenize

In [5]:
tokens      = set()
sentences   = []
for ep_summary in eps_summary:
    sents = sent_tokenize(ep_summary)
    sentences.extend(sents)
    for sent in sents:
        words = word_tokenize(sent)
        for word in words:
            if not word.lower() in overused_verbs_lowered:
                tokens.add(word.lower())

In [6]:
token_to_index = dict()
index_to_token = dict()
i = 0
for token in tokens:
    token_to_index[token] = i
    index_to_token[i] = token
    i += 1

In [7]:
character_to_index = dict()
index_to_character = dict()
i = 0
for character in characters:
    character_to_index[character.lower()] = i
    index_to_character[i] = character.lower()
    i += 1

In [8]:
import numpy as np

In [9]:
def get_subjects_in_sent(tokenized_sent):
    return list(map(lambda x : x[0], filter(lambda x: x[1] == 'NNP', tokenized_sent)))
#checkear set vs lista, hot encoded vs count vectorized para characters

In [10]:
hot_encoded_sentences   = np.zeros((len(sentences), len(token_to_index)))
hot_encoded_characters  = np.zeros((len(sentences), len(characters)))

i = 0
for sentence in sentences:
    words = word_tokenize(sentence)
    for word in words:
        if word in token_to_index:
            hot_encoded_sentences[i][token_to_index[word]] = 1
    tagged  = nltk.pos_tag(words)
    subjects = set(get_subjects_in_sent(tagged))
    for subject in subjects:
            if subject in characters:
                hot_encoded_characters[i][character_to_index[subject.lower()]] = 1
    i += 1
hot_encoded_sentences

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
sorted(hot_encoded_sentences.mean(axis=0), reverse=True)

[1.0,
 0.5532473212333261,
 0.5431882790290837,
 0.518259348349005,
 0.4277279685108244,
 0.36693636562431664,
 0.23923026459654495,
 0.22086157883227642,
 0.21626940739120928,
 0.2138639842554122,
 0.1758145637437131,
 0.172534441285808,
 0.15613382899628253,
 0.13732779357095998,
 0.13339164662147387,
 0.12989284933304177,
 0.1281434506888257,
 0.1277061010277717,
 0.12355127924775858,
 0.12333260441723158,
 0.10868139077192215,
 0.10736934178876012,
 0.09665427509293681,
 0.09009403017712661,
 0.08768860704132954,
 0.08090968729499234,
 0.07762956483708724,
 0.07478679204023617,
 0.07019462059916903,
 0.06953859610758802,
 0.06800787229389897,
 0.06538377432757489,
 0.06275967636125082,
 0.06254100153072381,
 0.061884977039142794,
 0.06144762737808878,
 0.06035425322545375,
 0.05947955390334572,
 0.05641810627596763,
 0.05138858517384649,
 0.05007653619068445,
 0.04767111305488738,
 0.042641591952766233,
 0.041985567461185216,
 0.038486770172753114,
 0.036737371528537066,
 0.0360813

In [12]:
hot_encoded_sentences.mean()

0.0025241490947683514

In [13]:
hot_encoded_sentences.std()

0.050177462730949265

In [14]:
outliers_right = np.where(hot_encoded_sentences.mean(axis=0) > hot_encoded_sentences.mean()+1.5*hot_encoded_sentences.std())
print(list(map(lambda x: index_to_token[x], outliers_right[0])))

['them', 'of', 'the', 'with', 'he', 'it', 'for', 'not', 'they', 'but', 'that', '.', 'and', 'her', 'him', 'she', 'are', 'magic', 'his', 'a', 'as', ',', 'to', 'is', 'in', "'s"]


In [15]:
for outlier in outliers_right[0]:
    overused_verbs_lowered.append(index_to_token[outlier])

In [16]:
tokens      = set()
sentences   = []
for ep_summary in eps_summary:
    sents = sent_tokenize(ep_summary)
    sentences.extend(sents)
    for sent in sents:
        words = word_tokenize(sent)
        for word in words:
            if not word.lower() in overused_verbs_lowered:
                tokens.add(word.lower())

In [17]:
token_to_index = dict()
index_to_token = dict()
i = 0
for token in tokens:
    token_to_index[token] = i
    index_to_token[i] = token
    i += 1

In [18]:
hot_encoded_sentences   = np.zeros((len(sentences), len(token_to_index)))
hot_encoded_characters  = np.zeros((len(sentences), len(characters)))

i = 0
for sentence in sentences:
    words = word_tokenize(sentence)
    for word in words:
        if word in token_to_index:
            hot_encoded_sentences[i][token_to_index[word]] = 1
    tagged  = nltk.pos_tag(words)
    subjects = set(get_subjects_in_sent(tagged))
    for subject in subjects:
            if subject in characters:
                hot_encoded_characters[i][character_to_index[subject.lower()]] = 1
    i += 1
hot_encoded_sentences

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
sorted(hot_encoded_sentences.mean(axis=0), reverse=True)

[0.07762956483708724,
 0.07478679204023617,
 0.07019462059916903,
 0.06953859610758802,
 0.06800787229389897,
 0.06538377432757489,
 0.06275967636125082,
 0.06254100153072381,
 0.061884977039142794,
 0.06144762737808878,
 0.06035425322545375,
 0.05947955390334572,
 0.05641810627596763,
 0.05138858517384649,
 0.05007653619068445,
 0.04767111305488738,
 0.042641591952766233,
 0.041985567461185216,
 0.038486770172753114,
 0.036737371528537066,
 0.03608134703695605,
 0.03498797288432101,
 0.03476929805379401,
 0.033238574240104964,
 0.03301989940957796,
 0.03258254974852395,
 0.030833151104307895,
 0.029521102121145858,
 0.029083752460091844,
 0.028865077629564837,
 0.028427727968510823,
 0.0275530286464028,
 0.02558495517165974,
 0.025147605510605728,
 0.024928930680078724,
 0.024710255849551718,
 0.024710255849551718,
 0.02449158101902471,
 0.02449158101902471,
 0.02383555652744369,
 0.02339820686638968,
 0.023179532035862673,
 0.022960857205335666,
 0.022304832713754646,
 0.022304832713

In [20]:
sorted(hot_encoded_sentences.mean(axis=0), reverse=False)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [21]:
outliers_left = np.where(hot_encoded_sentences.mean(axis=0) == 0)
print(list(map(lambda x: index_to_token[x], outliers_left[0])))

['evergreen', 'sitate', 'trace', 'east', 'grey', 'successful', 'pappitson', 'loyce', 'junior', 'peacocks', 'bell', 'zara', 'yeti', 'sukehiros', 'fanzell', 'towering', 'phati', 'acceptance', 'holy', 'helene', 'elmora', 'crumbling', 'neige', 'department', 'sorrow', 'avidya', 'langris', 'motivated', 'anastasis', 'lugner', 'avior', 'charmy', 'noonesheardofthis', 'ten', 'meteorite', 'peacock', 'gauche', 'maggie', 'nebra', 'vide', 'blunt', 'zephyr', 'leopolds', 'spectral', 'roulacase', 'silva', 'secre', 'mars', 'sky-splitting', 'letoile', 'green', 'selena', 'tormenta', 'reinforcement', 'general', 'hamon', 'thunderclap', 'marx', 'mogura', 'ado', 'gris', 'fifteen', 'diamond', 'meshu', 'buckshot', 'harpes', 'agrippa', 'lagris', 'ben', 'valkyrie', 'sukehiro', 'rill', 'enoteca', 'lingering', 'banisher', 'orca', 'exploding', 'crescent', 'luftair', 'midnight', 'violent', 'vaude', 'vanica', 'undine', 'closed', 'blizzard', 'scope', 'portaport', 'licht', 'kira', 'mantises', 'mimosa', 'summer', 'nest',

In [22]:
for outlier in outliers_left[0]:
    overused_verbs_lowered.append(index_to_token[outlier])

In [23]:
tokens      = set()
sentences   = []
for ep_summary in eps_summary:
    sents = sent_tokenize(ep_summary)
    sentences.extend(sents)
    for sent in sents:
        words = word_tokenize(sent)
        for word in words:
            if not word.lower() in overused_verbs_lowered:
                tokens.add(word.lower())

In [24]:
token_to_index = dict()
index_to_token = dict()
i = 0
for token in tokens:
    token_to_index[token] = i
    index_to_token[i] = token
    i += 1

In [25]:
hot_encoded_sentences   = np.zeros((len(sentences), len(token_to_index)))
hot_encoded_characters  = np.zeros((len(sentences), len(characters)))

i = 0
for sentence in sentences:
    words = word_tokenize(sentence)
    for word in words:
        if word in token_to_index:
            hot_encoded_sentences[i][token_to_index[word]] = 1
    tagged  = nltk.pos_tag(words)
    subjects = set(get_subjects_in_sent(tagged))
    for subject in subjects:
            if subject in characters:
                hot_encoded_characters[i][character_to_index[subject.lower()]] = 1
    i += 1
hot_encoded_sentences

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
sorted(hot_encoded_sentences.mean(axis=0), reverse=True)

[0.07762956483708724,
 0.07478679204023617,
 0.07019462059916903,
 0.06953859610758802,
 0.06800787229389897,
 0.06538377432757489,
 0.06275967636125082,
 0.06254100153072381,
 0.061884977039142794,
 0.06144762737808878,
 0.06035425322545375,
 0.05947955390334572,
 0.05641810627596763,
 0.05138858517384649,
 0.05007653619068445,
 0.04767111305488738,
 0.042641591952766233,
 0.041985567461185216,
 0.038486770172753114,
 0.036737371528537066,
 0.03608134703695605,
 0.03498797288432101,
 0.03476929805379401,
 0.033238574240104964,
 0.03301989940957796,
 0.03258254974852395,
 0.030833151104307895,
 0.029521102121145858,
 0.029083752460091844,
 0.028865077629564837,
 0.028427727968510823,
 0.0275530286464028,
 0.02558495517165974,
 0.025147605510605728,
 0.024928930680078724,
 0.024710255849551718,
 0.024710255849551718,
 0.02449158101902471,
 0.02449158101902471,
 0.02383555652744369,
 0.02339820686638968,
 0.023179532035862673,
 0.022960857205335666,
 0.022304832713754646,
 0.022304832713

In [27]:
sorted(hot_encoded_sentences.mean(axis=0), reverse=False)

[0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,
 0.00021867483052700635,


In [28]:
hot_encoded_sentences.mean()

0.001561240636131011

In [29]:
hot_encoded_sentences.std()

0.0394816813700621

In [30]:
np.where(np.sum(hot_encoded_sentences, axis=1) == 0)

(array([ 951, 1263, 1434, 3950, 4352]),)

In [31]:
hot_encoded_characters

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
hot_encoded_characters.sum(axis=0)

array([   5.,  372.,   23.,   75.,    9.,    3.,   99.,   59.,   29.,
         93.,  128.,   51.,   23.,  143.,   77.,   54.,    9.,  226.,
        305.,  100.,   93.,   45.,  101.,   11.,   43.,    8.,   44.,
         47.,   52., 1175.,   85.,  109.,  152.,   79.,   40.,  144.,
         11.,   37.,   28.,  188.,   78.,   20.,  120.,   75.,  281.])

In [33]:
count_vectorized_sentences  = np.zeros((len(sentences), len(token_to_index)))
count_vectorized_characters = np.zeros((len(sentences), len(characters)))
i = 0
for sentence in sentences:
    words = word_tokenize(sentence)
    for word in words:
        if word in token_to_index:
            count_vectorized_sentences[i][token_to_index[word]] += 1
    tagged  = nltk.pos_tag(words)
    subjects = get_subjects_in_sent(tagged)
    for subject in subjects:
            if subject in characters:
                count_vectorized_characters[i][character_to_index[subject.lower()]] += 1
    i += 1

In [34]:
count_vectorized_sentences[-1]

array([0., 0., 0., ..., 0., 0., 0.])

In [35]:
sentences[-1]

'Yuno thinks about how if only he was stronger and yells out.'

In [36]:
token_to_index["stronger"]

98

In [37]:
np.where(count_vectorized_sentences > 1)

(array([  12,   18,   21,   21,   25,   25,   25,   28,   29,   33,   36,
          37,   69,   80,  100,  148,  213,  223,  249,  266,  272,  301,
         304,  317,  339,  367,  373,  373,  410,  424,  430,  438,  473,
         474,  475,  501,  501,  510,  551,  605,  605,  640,  649,  652,
         654,  655,  657,  657,  657,  659,  737,  774,  775,  794,  801,
         804,  819,  876,  886,  896,  901,  906,  906,  906,  906,  906,
         906,  906,  906,  929,  944,  965,  968,  985,  988, 1004, 1043,
        1045, 1089, 1131, 1239, 1249, 1266, 1291, 1291, 1292, 1294, 1325,
        1334, 1351, 1354, 1371, 1371, 1374, 1395, 1396, 1396, 1396, 1406,
        1417, 1432, 1457, 1476, 1510, 1534, 1554, 1572, 1572, 1597, 1601,
        1677, 1691, 1707, 1740, 1773, 1780, 1785, 1801, 1804, 1821, 1822,
        1840, 1840, 1846, 1860, 1872, 1876, 1938, 1943, 1958, 1979, 1983,
        1983, 1983, 1988, 2001, 2002, 2004, 2007, 2007, 2008, 2008, 2010,
        2014, 2014, 2018, 2021, 2024, 

In [38]:
np.where(count_vectorized_characters != hot_encoded_characters)

(array([   6,    6,    7,   10,   14,   16,   43,   47,   50,   50,   65,
          77,   79,   88,  130,  173,  176,  235,  236,  249,  315,  316,
         353,  354,  369,  381,  394,  395,  397,  423,  460,  544,  574,
         602,  647,  649,  649,  654,  659,  667,  704,  733,  737,  740,
         765,  772,  777,  780,  784,  785,  791,  875,  906,  914,  919,
         930, 1077, 1081, 1126, 1131, 1155, 1167, 1172, 1212, 1249, 1295,
        1309, 1317, 1344, 1366, 1396, 1432, 1457, 1461, 1467, 1476, 1481,
        1503, 1503, 1506, 1528, 1580, 1603, 1607, 1637, 1666, 1703, 1744,
        1802, 1809, 1910, 1916, 1972, 1980, 1981, 1982, 1987, 1994, 2003,
        2005, 2009, 2014, 2035, 2051, 2055, 2056, 2058, 2060, 2061, 2067,
        2086, 2088, 2091, 2108, 2137, 2139, 2142, 2144, 2144, 2156, 2157,
        2161, 2162, 2162, 2170, 2178, 2191, 2195, 2197, 2199, 2201, 2206,
        2217, 2228, 2242, 2256, 2261, 2292, 2296, 2301, 2304, 2305, 2314,
        2323, 2334, 2335, 2338, 2362, 

In [39]:
u = 4570
i = 3626
print(count_vectorized_sentences[u][i])
print(hot_encoded_sentences[u][i])
print(index_to_token[i])

0.0
0.0
springs


In [40]:
import json

In [41]:
def write_json(to_json, filename):
    json_object = json.dumps(to_json)

    with open(filename, "w") as outfile:
        outfile.write(json_object)

In [42]:
write_json(hot_encoded_characters.tolist(),      "4_hot_encoded_characters_black_clover.json")
write_json(hot_encoded_sentences.tolist(),       "4_hot_encoded_sentences_black_clover.json")
write_json(count_vectorized_characters.tolist(), "4_count_vectorized_characters_black_clover.json")
write_json(count_vectorized_sentences.tolist(),  "4_count_vectorized_sentences_black_clover.json")
write_json(index_to_token,                       "4_index_to_token_black_clover.json")
write_json(token_to_index,                       "4_token_to_index_black_clover.json")
write_json(index_to_character,                   "4_index_to_character_black_clover.json")
write_json(character_to_index,                   "4_character_to_index_black_clover.json")