In [27]:
import json
import numpy as np
import matplotlib.pyplot as plt

In [28]:
def read_json(filename):    
    with open(filename, 'r') as openfile:
        return json.load(openfile)

In [29]:
hot_encoded_characters = np.array(read_json("4_hot_encoded_characters_black_clover.json"))
hot_encoded_sentences  = np.array(read_json("4_hot_encoded_sentences_black_clover.json"))

count_vectorized_characters = np.array(read_json("4_count_vectorized_characters_black_clover.json"))
count_vectorized_sentences  = np.array(read_json("4_count_vectorized_sentences_black_clover.json"))

index_to_character = read_json("4_index_to_character_black_clover.json")
character_to_index = read_json("4_character_to_index_black_clover.json")

index_to_token = read_json("4_index_to_token_black_clover.json")
token_to_index = read_json("4_token_to_index_black_clover.json")

In [30]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [31]:
X = StandardScaler().fit_transform(hot_encoded_sentences)

In [32]:
X

array([[-0.0330843 , -0.04681389, -0.04910421, ..., -0.02091748,
        -0.01478928, -0.01478928],
       [-0.0330843 , -0.04681389, -0.04910421, ..., -0.02091748,
        -0.01478928, -0.01478928],
       [-0.0330843 , -0.04681389, -0.04910421, ..., -0.02091748,
        -0.01478928, -0.01478928],
       ...,
       [-0.0330843 , -0.04681389, -0.04910421, ..., -0.02091748,
        -0.01478928, -0.01478928],
       [-0.0330843 , -0.04681389, -0.04910421, ..., -0.02091748,
        -0.01478928, -0.01478928],
       [-0.0330843 , -0.04681389, -0.04910421, ..., -0.02091748,
        -0.01478928, -0.01478928]])

In [33]:
def project(dir, vec):
    return (np.sqrt(np.matmul(dir,np.transpose(vec)))*dir)/np.matmul(dir,np.transpose(dir))

In [34]:
for i in range(0, hot_encoded_sentences.shape[0]):
    curr_word       = np.zeros((1, hot_encoded_sentences.shape[1]))
    curr_word[0][1501] = 1
    print(project(curr_word, hot_encoded_sentences[i])[0][1501])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [35]:
#kmeans = KMeans(n_clusters=10, random_state=0).fit(X)
#clusters = dict()
#for i in range(0, hot_encoded_sentences.shape[1]):
#    curr_word       = np.zeros((1, hot_encoded_sentences.shape[1]))
#    curr_word[0][i] = 1
#    prediction      = kmeans.predict(curr_word)
#    curr_word_text  = index_to_token[str(i)]
#    print(curr_word_text, prediction)


In [36]:
import keras
import sklearn.model_selection
import numpy as np
import pandas as pd

In [37]:
x_train, x_valid, y_train, y_valid = sklearn.model_selection.train_test_split(hot_encoded_characters, hot_encoded_sentences, test_size=0.3, random_state=0)

In [38]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
callback_early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, verbose=0, mode='auto')

In [40]:
model2 = keras.models.Sequential()
model2.add(keras.layers.BatchNormalization(input_shape=tuple([x_train.shape[1]])))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1], activation='sigmoid'))
model2.add(keras.layers.core.Dense(hot_encoded_sentences.shape[1],   activation='softmax'))
model2.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])
print(model2.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 batch_normalization_1 (Batc  (None, 45)               180       
 hNormalization)                                                 
                                                                 
 dense_9 (Dense)             (None, 5016)              230736    
                                                                 
 dense_10 (Dense)            (None, 5016)              25165272  
                                                                 
 dense_11 (Dense)            (None, 5016)              25165272  
                                                                 
 dense_12 (Dense)            (None, 5016)              25165272  
                                                                 
 dense_13 (Dense)            (None, 5016)              25165272  
                                                      

In [41]:
model2.fit(x_train, y_train, batch_size=100, epochs=1000, validation_data=(x_valid, y_valid), verbose=1, callbacks=[callback_early_stopping])

Epoch 1/1000
33/33 [==============================] - 23s 678ms/step - loss: 67.4624 - accuracy: 0.0000e+00 - val_loss: 66.6221 - val_accuracy: 0.0000e+00
Epoch 2/1000
33/33 [==============================] - 23s 708ms/step - loss: 66.8991 - accuracy: 0.0000e+00 - val_loss: 66.1081 - val_accuracy: 0.0000e+00
Epoch 3/1000
33/33 [==============================] - 23s 707ms/step - loss: 66.3737 - accuracy: 0.0000e+00 - val_loss: 65.6262 - val_accuracy: 0.0022
Epoch 4/1000
33/33 [==============================] - 23s 710ms/step - loss: 65.8731 - accuracy: 6.2480e-04 - val_loss: 65.1473 - val_accuracy: 0.0000e+00
Epoch 5/1000
33/33 [==============================] - 23s 709ms/step - loss: 65.3803 - accuracy: 0.0000e+00 - val_loss: 64.6900 - val_accuracy: 0.0000e+00
Epoch 6/1000
33/33 [==============================] - 23s 710ms/step - loss: 64.9063 - accuracy: 0.0000e+00 - val_loss: 64.2534 - val_accuracy: 0.0000e+00
Epoch 7/1000
33/33 [==============================] - 23s 708ms/step - los

In [42]:
character_to_index['yuno']

18

In [43]:
yuno = np.zeros((1, len(character_to_index)))
yuno[0][18] = 1
yuno

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
for i in model2.predict(yuno)[0]:
    print(i)

1/1 [==============================] - 0s 104ms/step
9.114939e-05
6.503718e-05
0.00014433499
4.2001615e-05
2.898027e-05
0.000112156784
6.138915e-05
8.8619345e-05
3.8262497e-05
3.217344e-05
0.000119339784
0.0003306247
7.435172e-05
6.466058e-05
0.00026467032
1.8688535e-05
3.7528138e-05
0.00010156436
0.00032452852
5.7637037e-05
6.397708e-05
4.3875196e-05
1.9366307e-05
0.00015620122
0.00012555209
5.0745337e-05
1.954696e-05
0.00012848499
0.00040487916
1.2161286e-05
4.9366543e-05
2.3767661e-05
0.00025730443
4.5149573e-05
5.9318256e-05
5.3044074e-05
2.4987521e-05
7.3459465e-05
2.9787567e-05
4.8581165e-05
0.00019903512
0.001749516
2.4810146e-05
0.00010934651
0.00010129738
0.0015674566
8.996992e-05
3.798469e-05
4.0659328e-05
1.6368733e-05
9.41361e-05
0.00010578062
1.7843638e-05
1.3412059e-05
4.9767204e-05
3.8344322e-05
8.207248e-05
3.373148e-05
0.005534253
2.5632698e-05
1.1744114e-05
5.0127983e-05
0.0001816188
4.0687122e-05
0.00018211649
0.0001325868
2.7305909e-05
2.8410082e-05
1.0707312e-05
8.

In [45]:
a_yuno = model2.predict(yuno)
a2_yuno = model2.predict(yuno)

1/1 [==============================] - 0s 46ms/step


In [46]:
print(np.where(a_yuno == np.max(a_yuno)))
print(np.where(a2_yuno == np.max(a2_yuno)))

(array([0]), array([2472]))
(array([0]), array([2472]))


In [54]:
a_yuno[0][2472]

0.054464214

In [55]:
print(index_to_token['0'], index_to_token['2472'])

tools on


In [49]:
character_to_index['yami']

44

In [50]:
asta = np.zeros((1, len(character_to_index)))
asta[0][44] = 1

a_asta = model2.predict(asta)

1/1 [==============================] - 0s 44ms/step


In [51]:
np.where(a_asta == np.max(a_asta))

(array([0]), array([2472]))

In [53]:
print(index_to_token['0'], index_to_token['2472'])

tools on


In [78]:
ind = np.argpartition(a_asta[0], -100)[-100:]
ind

array([ 224,  440, 3158,  206, 1004,  259, 4211, 1018,  980, 4909, 4054,
       1413,  916,   41, 1439, 3683,  863, 3613, 2593, 4291, 4796,  235,
       2298, 2508, 2284, 1085, 5000, 1737, 1744, 4945, 2871, 1779, 4948,
        648,  632, 2518,   45, 1801, 4453, 2905, 4544, 2952, 2181, 3960,
       1252, 2102, 4092,   58, 4952, 1292, 1299, 3879, 2472, 3816, 2664,
       1321,   97, 3893, 1358, 3900,  106, 4051, 1365, 2447, 2441, 2697,
       4886,  134, 1449, 3687, 2722,  152,  868, 2741, 3629, 1590, 4841,
       4331, 2321, 1674, 1676, 2840, 1082,  701, 1723, 4397, 4427, 1804,
       3318, 3185, 3150, 4010, 2030, 2046, 3956,  365, 3010, 3022, 2089,
       1906])

In [79]:
for i in ind:
    print(a_asta[0][i], '\t', index_to_token[str(i)])

0.0008853046 	 why
0.0009211138 	 immediately
0.0009337024 	 too
0.000951661 	 both
0.0009532614 	 situation
0.00096346985 	 outside
0.0009807572 	 were
0.0010083113 	 there
0.0011354145 	 elves
0.0014315746 	 should
0.001077962 	 decides
0.0012696102 	 each
0.0011782942 	 dungeon
0.0017495174 	 more
0.001629843 	 day
0.0013852245 	 thinks
0.0010992987 	 making
0.0012611896 	 some
0.0013521495 	 down
0.0011647283 	 kill
0.0011571606 	 leave
0.0011084322 	 doing
0.0010412096 	 only
0.0011222969 	 humans
0.0019461148 	 like
0.0019251577 	 sword
0.0012990091 	 where
0.0015695594 	 himself
0.0011682196 	 spell
0.0015863394 	 mana
0.0018239411 	 wonders
0.0018194083 	 first
0.0011076328 	 after
0.0018934405 	 base
0.0011283543 	 friends
0.0012935015 	 hit
0.0015674566 	 states
0.0017712585 	 two
0.0010973819 	 ground
0.0013545792 	 stop
0.0011084778 	 time
0.0010149082 	 offers
0.0011331595 	 everyone
0.0010952456 	 notices
0.0010144005 	 appears
0.0019507089 	 tries
0.053320862 	 be
0.0055

In [73]:
model2.evaluate(x_valid, y_valid)

43/43 [==============================] - 2s 45ms/step - loss: 60.7117 - accuracy: 0.0022


[60.711666107177734, 0.002186588943004608]